### ISSUE TITLE
Crash on node 10.6.0 and up

### ISSUE THREAD

**Issue by Ky6uk** [webpack/webpack-dev-server#1449]
* Operating System: macOS 10.13.6
* Node Version: 10.6.0, 10.7.0
* NPM Version: 6.1.0
* webpack Version: 4.16.3
* webpack-dev-server Version: 3.1.5

- [x] This is a **bug**
- [x] This is a **modification** request

Webpack crashes sometimes in node `10.6.0` and up. Unfortunately I can't localize that problem, but I think this is relating to https://github.com/nodejs/node/issues/21665.

**Comment by blackshadev** [comment]
@evilebottnawi  this was one of the issues that moved me to webpack-serve since it completely broke webpack-dev-server with https  for me.

**Comment by evilebottnawi** [comment]
Problem still exists?

**Comment by Ky6uk** [comment]
@evilebottnawi I am not sure, because I am using node `v10.5.0` because of the bug. I will try to use the latest node from now. Let's see.

**Comment by blackshadev** [comment]
Good to hear. I will upgrade my setup next week and report back with the
results.

**Comment by blackshadev** [comment]
@evilebottnawi Seems to work just fine. Thanks!

**Comment by jrop** [comment]
I am getting this in an app created with `create-react-app` under node 10.9.0

**Comment by blackshadev** [comment]
@jrop Which version of webpack-dev-server are you running. For me this is absolutely fixed in webpack-dev-server version 3.1.7

**Comment by jrop** [comment]
@blackshadev 

macOS 10.13.6
webpack-dev-server 2.9.4

I created the app using `create-react-app --scripts-version react-scripts-ts`.   As others have noted, rebooting the machine causes the issue to go away for a limited time.  But then it comes right back.  I have switched to using Node 8.11.4 and the issue has ceased to occur.

**Comment by evilebottnawi** [comment]
@jrop you should update `webpack-dev-server`

**Comment by jrop** [comment]
@evilebottnawi I believe the responsible party to upgrading `webpack-dev-server` is the [team maintaining `react-scripts-ts`](https://github.com/wmonk/create-react-app-typescript/blob/master/package.json#L52), which is why I have resorted to using an older version of Node instead

**Comment by WellspringCS** [comment]
So... five hours later, and I've not seen the error yet. I still have the occasional "The expression evaluated to a falsy value" crash, but moving back to 10.5... I count it as a huge win.

For me, at least, webpack-dev-server 3.1.7 proved to be a false hope.
