### ISSUE TITLE
Module exports are not preserved when using dev-server with Webpack 5 beta

### ISSUE THREAD

**Issue by csvn** [webpack/webpack-dev-server#2484]
- Operating System: Windows 10
- Node Version: v13.10.0
- NPM Version: 6.13.7
- webpack Version: 5.0.0-beta.14
- webpack-dev-server Version: 3.10.13
- Browser: Chrome v82

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

Reproduction link: https://github.com/csvn/webpack-dev-server-export-issue-reproduction

```js
// webpack.config.js
module.exports = {
  mode: 'development',
  entry: './src/main.js',
  output: {
    ecmaVersion: 2015,
    library: 'main',
    libraryTarget: 'window'
  },
  devServer: {
    port: 3001,
    contentBase: require('path').join(__dirname, 'public'),
    open: false
  }
};
```

```js
// src/main.js
export const greeting = 'Hello World!';
```

#### Additional details

The entry point is messed up when when running `webpack-dev-server`. The exports will always be empty (`{}`) due to `webpack-dev-server` [prepending it's entry points](https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/addEntries.js#L142), which does not seem to yield the correct results with Webpack 5 beta.

##### When using `webpack-dev-server`
```js
/******/ 	// Load entry module and return exports
/******/ 	__webpack_require__("./src/main.js");
/******/ 	return __webpack_require__("./node_modules/webpack-dev-server/client/index.js?http://localhost:3001");
```

##### When using `webpack` build
```js
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__("./src/main.js");
```

### Expected Behavior
Values exported from `main.js` should be available on `window.main`.

### Actual Behavior
The exported object on `window.main` is `{}`

### How can we reproduce the behavior?
1. Clone the repo from the link above
2. Run `npm start` (or `npx webpack-dev-server`
3. Open http://localhost:3001
4. There are error in console due to export from `main.js` missing

**Comment by evilebottnawi** [comment]
Pr welcome

**Comment by hmnd** [comment]
A workaround for now at least is to set `config.devServer.injectClient: false`; this prevents dev-server from prepending its entry.

**Comment by Loonride** [comment]
> /cc @Loonride Can you look at this?

I will take a look

**Comment by kamilic** [comment]
this problem still existed on webpack@5.1.0.

**Comment by sprilukin** [comment]
this problem is still present in webpack@5.3.2

**Comment by sprilukin** [comment]
I still want liveReloading capability during developing of may library so i found a workaround.
original webpack config: 
```
const config = (env, args) => {
    ...
    entry: './src/myLibrary'
    ...
}
```

modified webpack config:
```
const config = (env, args) => {
    const {devServer = false} = env;
    ...
    entry: devServer ? ['webpack-dev-server/client', './src/myLibrary'] : './src/myLibrary'
    devServer: {
       ...
       injectClient: true
    }
}
```

works fine despite the fact that correct injection of the dev server client should be the following:
`webpack-dev-server/client?http://<webpackConfig.devServer.host>:<webpackConfig.devServer.port>`

But i'm looking forward to see this issue fixed.

**Comment by erikwatson** [comment]
This is still an issue for me. 

```json
"devDependencies": {
    "webpack": "^5.4.0",
    "webpack-cli": "^4.2.0",
    "webpack-dev-server": "^3.11.0",
}
```

**Comment by ylemkimon** [comment]
Duplicate of #2692 (it's a newer issue, but has more details).

**Comment by evilebottnawi** [comment]
@ylemkimon yep, but it is different issues, but have the same origin

**Comment by evilebottnawi** [comment]
@ylemkimon just check, do we have test for:
- https://github.com/webpack/webpack-dev-server/issues/2692
- and for this

**Comment by ylemkimon** [comment]
@evilebottnawi :smile: https://github.com/webpack/webpack-dev-server/blob/e647af47e7b8dec4dc769a2e408b3a530b6882c2/test/integration/ModuleFederation.test.js#L27-L53

**Comment by evilebottnawi** [comment]
@ylemkimon good, for library?

**Comment by ylemkimon** [comment]
@evilebottnawi It tests for `libraryTarget: 'umd'`: https://github.com/webpack/webpack-dev-server/blob/1aa0d2db699d3d9edad7d354b4501d2773aa3675/test/fixtures/module-federation-config/webpack.config.js#L10

**Comment by evilebottnawi** [comment]
@ylemkimon I mean testing `libraryTarget` without module federation, sorry for misleading

**Comment by cyulin** [comment]
this problem is still present in webpack@5.10.3

**Comment by csvan** [comment]
@cyulin webpack-dev-server 4 is in Beta and has support for Webpack 5. You can test it out and report any issues you find.

**Comment by kekeqy** [comment]
this problem is still present in webpack@5.11.0

**Comment by cyulin** [comment]
> this problem is still present in webpack@5.11.0

use webpack-dev-server@4

**Comment by kekeqy** [comment]
> > this problem is still present in webpack@5.11.0
> 
> use webpack-dev-server@4
It does work. I'm looking forward to the official version soon.

**Comment by danGiacomelli** [comment]
I started to use `webpack-dev-server@4.0.0-beta.0`. It really does work.

**Comment by ncastaldo** [comment]
I used `webpack-dev-server@4.0.0-beta.0` and it worked! Thank you @danGiacomelli!
In `webpack.config.js` I also had to modify `contentBase` into `static`

```
...
devServer: {
  contentBase: path.resolve(__dirname, 'test'),
  compress: true,
  port: 8080
}
```

into

```
...
devServer: {
  static: path.resolve(__dirname, 'test'),
  compress: true,
  port: 8080
}
```

**Comment by alexander-akait** [comment]
Let's close because fixed in beta, in near future we will do new release with more fixes and features

**Comment by Mustang-Galaxy** [comment]
webpack-dev-server@4.0.0-beta.0 is work

**Comment by alexander-akait** [comment]
remove `client.host`, you should not touch this option if you don't use proxy server above dev, i.e. nginx -> dev server

**Comment by bturner1273** [comment]
still an issue for me as well in webpack 5.28.0 with dev-server 4.0.0-beta.1 and cli 4.6.0. Solved this by just setting the window library explicitly in my index.js i.e.

```
window["export_name"] = {
    function_to_export: your_function
}
```
then in any js script can now access window.export_name.function_to_export

**Comment by alexander-akait** [comment]
We have tests on it, double check your version or provide example of the problem

**Comment by turansky** [comment]
Works for me with `webpack-dev-server:4.0.0-beta.2`

**Comment by lovefishs** [comment]
Works for me with

```json
{
  "@pmmmwh/react-refresh-webpack-plugin": "0.5.0-rc.3",
  "react-refresh": "0.10.0",
  "webpack-cli": "4.8.0",
  "webpack-dev-server": "4.0.0-rc.1"
}
```

**Comment by alex-vukov** [comment]
Having the same problem with the latest possible setup + Module Federation Plugin:
```
{
    "webpack": "^5.64.2",
    "webpack-cli": "^4.9.1",
    "webpack-dev-server": "^4.5.0",
}
```

This is in remoteEntry.js and I can't disable it because `config.devServer.injectClient: false` no longer works in this version of dev server
```
/************************************************************************/
/******/ 	
/******/ 	// module cache are used so entry inlining is disabled
/******/ 	// startup
/******/ 	// Load entry module and return exports
/******/ 	__webpack_require__.O(undefined, ["vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_0_0_0_0_port_-9d6a35","webpack_sharing_provide_default_ccp_utils-webpack_sharing_provide_default_i18next-webpack_sha-7bf979"], () => (__webpack_require__("./node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=0.0.0.0&port=5103&pathname=%2Fws&logging=info&reconnect=10")))
/******/ 	__webpack_require__.O(undefined, ["vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_0_0_0_0_port_-9d6a35","webpack_sharing_provide_default_ccp_utils-webpack_sharing_provide_default_i18next-webpack_sha-7bf979"], () => (__webpack_require__("./node_modules/webpack/hot/dev-server.js")))
/******/ 	var __webpack_exports__ = __webpack_require__.O(undefined, ["vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_0_0_0_0_port_-9d6a35","webpack_sharing_provide_default_ccp_utils-webpack_sharing_provide_default_i18next-webpack_sha-7bf979"], () => (__webpack_require__("webpack/container/entry/onboardingMFE")))
/******/ 	__webpack_exports__ = __webpack_require__.O(__webpack_exports__);
/******/ 	onboardingMFE = __webpack_exports__;
/******/ 	
/******/ })()
;
//# sourceMappingURL=sourcemaps/remoteEntry.js.map
```

**Comment by alex-vukov** [comment]
> Having the same problem with the latest possible setup + Module Federation Plugin:
> 
> ```
> {
>     "webpack": "^5.64.2",
>     "webpack-cli": "^4.9.1",
>     "webpack-dev-server": "^4.5.0",
> }
> ```
> 
> This is in remoteEntry.js and I can't disable it because `config.devServer.injectClient: false` no longer works in this version of dev server
> 
> ```
> /************************************************************************/
> /******/ 	
> /******/ 	// module cache are used so entry inlining is disabled
> /******/ 	// startup
> /******/ 	// Load entry module and return exports
> /******/ 	__webpack_require__.O(undefined, ["vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_0_0_0_0_port_-9d6a35","webpack_sharing_provide_default_ccp_utils-webpack_sharing_provide_default_i18next-webpack_sha-7bf979"], () => (__webpack_require__("./node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=0.0.0.0&port=5103&pathname=%2Fws&logging=info&reconnect=10")))
> /******/ 	__webpack_require__.O(undefined, ["vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_0_0_0_0_port_-9d6a35","webpack_sharing_provide_default_ccp_utils-webpack_sharing_provide_default_i18next-webpack_sha-7bf979"], () => (__webpack_require__("./node_modules/webpack/hot/dev-server.js")))
> /******/ 	var __webpack_exports__ = __webpack_require__.O(undefined, ["vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_0_0_0_0_port_-9d6a35","webpack_sharing_provide_default_ccp_utils-webpack_sharing_provide_default_i18next-webpack_sha-7bf979"], () => (__webpack_require__("webpack/container/entry/onboardingMFE")))
> /******/ 	__webpack_exports__ = __webpack_require__.O(__webpack_exports__);
> /******/ 	onboardingMFE = __webpack_exports__;
> /******/ 	
> /******/ })()
> ;
> //# sourceMappingURL=sourcemaps/remoteEntry.js.map
> ```

If anyone is interested, the extra entry points disappeared after I set `webSocketServer: false` into `devServer: {}`

**Comment by yxw007** [comment]
```javascript
...
output: {
		library: "GlobalName",
		path: path.resolve(__dirname, 'dist'),
		filename: 'index.js',
		libraryTarget: 'umd',
		libraryExport: 'default'
},
...
```
This is accessed via GlobalName， work's ok in webpack5.x
