### ISSUE TITLE
HMR/Live Reloading broken after Webpack 5 rc.0 -> rc.1 update

### ISSUE THREAD

**Issue by wojtekmaj** [webpack/webpack-dev-server#2758]
- Operating System: macOS Big Sur 
- Node Version: 14.5.0
- NPM Version: 6.14.5
- webpack Version: 5.0.0-rc.3
- webpack-dev-server Version: ^3.10.3
- Browser: Chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

After upgrading from Webpack `5.0.0-beta.29` to `5.0.0-rc.3`, I've noticed that HMR/Live Reloading stopped working, even though no other changes to the code were made.

I investigated by updating it step by step and here's my outcome:

| Version | Works? |
| -- | -- |
| 5.0.0-beta.29 | Yes ✅  |
| 5.0.0-beta.30 | Yes ✅  |
| 5.0.0-beta.31 | Yes ✅  |
| 5.0.0-beta.32 | Yes ✅  |
| 5.0.0-beta.33 | Yes ✅  |
| 5.0.0-rc.0 | Yes ✅  |
| 5.0.0-rc.1 | No ❌  |
| 5.0.0-rc.2 | No ❌  |
| 5.0.0-rc.3 | No ❌  |

### Code

```js
// webpack.config.js
const webpack = require('webpack');
const path = require('path');

const HtmlWebpackPlugin = require('html-webpack-plugin');

const isProduction = process.env.NODE_ENV === 'production';
const isDevelopment = !isProduction;

const publicPath = process.env.PUBLIC_URL || '/';

module.exports = {
  mode: isProduction ? 'production' : 'development',
  bail: isProduction,
  entry: {
    src: [
      './src/index.jsx',
    ],
  },
  output: {
    path: path.resolve(__dirname, 'dist'),
    publicPath,
  },
  resolve: {
    extensions: ['.js', '.jsx'],
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        include: path.resolve(__dirname, 'src'),
        use: 'babel-loader',
      },
    ].filter(Boolean),
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: './src/index.html'
    }),
  ].filter(Boolean),
  devServer: {
    historyApiFallback: true,
    hot: true,
    port: 3000,
  },
};
```

### Expected Behavior

HMR to work on Webpack version `5.0.0-rc.1` to `5.0.0-rc.3`.

Console output in `5.0.0-beta.29` to `5.0.0-rc.0`:

```
[HMR] Waiting for update signal from WDS...
[WDS] Hot Module Replacement enabled.
[WDS] Live Reloading enabled.
```
...and of course, on change...
```
[WDS] App updated. Recompiling...
[WDS] App updated. Recompiling...
[WDS] App hot update...
[HMR] Checking for updates on the server...
[HMR] Updated modules:
[HMR]  - ./components/pages/index.jsx
[HMR] App is up to date.
```

### Actual Behavior

HMR doesn't on Webpack version `5.0.0-rc.1` to `5.0.0-rc.3`.

Console output in `5.0.0-rc.3`:

```
[HMR] Waiting for update signal from WDS...
```
...and silence after that.

I can see that Webpack is rebuilding, so I think Webpack part works fine. Refreshing the page manually also gets me the updated page. So only HMR/Live Reloading part must be broken.

**Comment by evilebottnawi** [comment]
Please create reproducible test repo, I think bug in `webpack-dev-server`

**Comment by wojtekmaj** [comment]
Managed to narrow it down quite a lot.

[Webpack HMR bug repro.zip](https://github.com/webpack/webpack-dev-server/files/5333711/Webpack.HMR.bug.repro.zip)

**Comment by wojtekmaj** [comment]
Interestingly, removing `.browserlistrc` seems to fix the issue.

So I compared src.js in both cases looking for answer and found that:

**With** .browserlistrc (no: when HMR not working) `src.js` ends with:

```js
/******/ 	
/************************************************************************/
/******/ 	// module cache are used so entry inlining is disabled
/******/ 	// startup
/******/ 	// Load entry module
/******/ 	__webpack_require__("./src/index.jsx");
/******/ 	__webpack_require__("./node_modules/webpack/hot/dev-server.js");
/******/ })()
;
```

and **without** .browserlistrc (no: when HMR is working), `src.js` ends with:

```js
/************************************************************************/
/******/ 	// module cache are used so entry inlining is disabled
/******/ 	// startup
/******/ 	// Load entry module
/******/ 	__webpack_require__("./src/index.jsx");
/******/ 	__webpack_require__("./node_modules/webpack-dev-server/client/index.js?http://localhost:3000");
/******/ 	__webpack_require__("./node_modules/webpack/hot/dev-server.js");
/******/ })()
;
```

**Comment by evilebottnawi** [comment]
@wojtekmaj Can you provide `.browserlistrc`?

**Comment by evilebottnawi** [comment]
Looks webpack-dev-server thinks it is not browser

**Comment by wojtekmaj** [comment]
An example is in the repro repo linked above, but I tested these and all of them broke the build for me:

```
Chrome >=72
ChromeAndroid >=73
Edge >= 17
Firefox >=66
IE >=11
iOS >=11
Safari >=12.1
Samsung >=9.2
```

```
Chrome >=72
Firefox >=66
IE >=11
```

```
Chrome >=72
```

```
Chrome >=84
```

**Comment by wojtekmaj** [comment]
@evilebottnawi looks like your diagnosis is correct, because adding `target: 'web'` (which overwrites the default being `'browserlist'` since `5.0.0-rc.1`) to Webpack config resolves the issue.

**Comment by evilebottnawi** [comment]
Yes, we need to fix it in webpack-dev-server, hope I will find time on it, anyway you can send a PR

**Comment by khalwat** [comment]
I too am experiencing this issue, which renders HMR inoperative with webpack 5

**Comment by khalwat** [comment]
I can confirm that it works as expected with webpack `5.0.0-rc.0` but breaks with `5.0.0-rc.1` so the error is here somewhere:

https://github.com/webpack/webpack/compare/v5.0.0-rc.0..v5.0.0-rc.1

https://github.com/webpack/webpack/releases/tag/v5.0.0-rc.1

**Comment by chenxsan** [comment]
I've pushed a pull request to fix it, can anyone with the problem try the branch with yarn's resolution?

```
  "resolutions": {
    "webpack-dev-server": "git://github.com/chenxsan/webpack-dev-server#bugfix/fix-hmr-browserslist"
  }
```

**Comment by khalwat** [comment]
Using that @chenxsan I get:

```
webpack_1  | > webpack-dev-server --config webpack.dev.js --trace-deprecation
webpack_1  |
webpack_1  | Error: Cannot find module '../../client/'
webpack_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
webpack_1  |     at Function.resolve (internal/modules/cjs/helpers.js:19:19)
webpack_1  |     at addEntries (/var/www/project/buildchain/node_modules/webpack-dev-server/lib/utils/addEntries.js:39:36)
webpack_1  |     at updateCompiler (/var/www/project/buildchain/node_modules/webpack-dev-server/lib/utils/updateCompiler.js:48:5)
webpack_1  |     at new Server (/var/www/project/buildchain/node_modules/webpack-dev-server/lib/Server.js:72:5)
webpack_1  |     at startDevServer (/var/www/project/buildchain/node_modules/webpack-dev-server/bin/webpack-dev-server.js:106:14)
webpack_1  |     at processOptions (/var/www/project/buildchain/node_modules/webpack-dev-server/bin/webpack-dev-server.js:166:3)
webpack_1  |     at findPort.then (/var/www/project/buildchain/node_modules/webpack-dev-server/lib/utils/processOptions.js:33:9)
webpack_1  |     at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:52:5)
webpack_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
webpack_1  |     at internal/main/run_main_module.js:21:11
webpack_1  | npm ERR! code ELIFECYCLE
webpack_1  | npm ERR! errno 1
webpack_1  | npm ERR! example-project@1.1.3 debug: `webpack-dev-server --config webpack.dev.js --trace-deprecation`
webpack_1  | npm ERR! Exit status 1
webpack_1  | npm ERR!
webpack_1  | npm ERR! Failed at the example-project@1.1.3 debug script.
webpack_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
webpack_1  |
webpack_1  | npm ERR! A complete log of this run can be found in:
webpack_1  | npm ERR!     /root/.npm/_logs/2020-10-12T05_14_22_391Z-debug.log
fwt_webpack_1 exited with code 1
```

**Comment by chenxsan** [comment]
> Using that @chenxsan I get:
> 
> ```
> webpack_1  | > webpack-dev-server --config webpack.dev.js --trace-deprecation
> webpack_1  |
> webpack_1  | Error: Cannot find module '../../client/'
> webpack_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
> webpack_1  |     at Function.resolve (internal/modules/cjs/helpers.js:19:19)
> webpack_1  |     at addEntries (/var/www/project/buildchain/node_modules/webpack-dev-server/lib/utils/addEntries.js:39:36)
> webpack_1  |     at updateCompiler (/var/www/project/buildchain/node_modules/webpack-dev-server/lib/utils/updateCompiler.js:48:5)
> webpack_1  |     at new Server (/var/www/project/buildchain/node_modules/webpack-dev-server/lib/Server.js:72:5)
> webpack_1  |     at startDevServer (/var/www/project/buildchain/node_modules/webpack-dev-server/bin/webpack-dev-server.js:106:14)
> webpack_1  |     at processOptions (/var/www/project/buildchain/node_modules/webpack-dev-server/bin/webpack-dev-server.js:166:3)
> webpack_1  |     at findPort.then (/var/www/project/buildchain/node_modules/webpack-dev-server/lib/utils/processOptions.js:33:9)
> webpack_1  |     at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:52:5)
> webpack_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
> webpack_1  |     at internal/main/run_main_module.js:21:11
> webpack_1  | npm ERR! code ELIFECYCLE
> webpack_1  | npm ERR! errno 1
> webpack_1  | npm ERR! example-project@1.1.3 debug: `webpack-dev-server --config webpack.dev.js --trace-deprecation`
> webpack_1  | npm ERR! Exit status 1
> webpack_1  | npm ERR!
> webpack_1  | npm ERR! Failed at the example-project@1.1.3 debug script.
> webpack_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> webpack_1  |
> webpack_1  | npm ERR! A complete log of this run can be found in:
> webpack_1  | npm ERR!     /root/.npm/_logs/2020-10-12T05_14_22_391Z-debug.log
> fwt_webpack_1 exited with code 1
> ```

Sorry, have no idea what's going on here. Maybe you can remove the resolution and try to edit `lib/utils/addEntries` directly? Just add a `browserslist` in the `webTarget` array. I've tested on my computer with the example code @wojtekmaj  provides, it seems to be working fine with both webpack 5.0.0-rc.3 and webpack 5.

**Comment by slightlyfaulty** [comment]
@chenxsan's fix works for me.

Seems this issue happens when you have a `browserslist` entry in your `package.json`. Modules from `./node_modules/webpack-dev-server/client/` are not included in the output bundle at all. After removing `browserslist`, they are included correctly.

**Comment by chenxsan** [comment]
@slightlyfaulty You're right here. As of webpack v5.0.0-rc.1 https://github.com/webpack/webpack/releases/tag/v5.0.0-rc.1, the `target` defaults to `browserslist` if you have browserslist in your project. But `webpack-dev-server` is not updated yet to follow that change. I think that's why client parts are not included, resulting no socket connected to the server to watch updates.

**Comment by thermarthae** [comment]
Not sure if that helps, but it looks like this problem also occurs when the target is an array.
For example: `target: 'web'` works, but `target: ['web']` don't.

**Comment by leodr** [comment]
> Not sure if that helps, but it looks like this problem also occurs when the target is an array.
> For example: `target: 'web'` works, but `target: ['web']` don't.

Yup, the ability to set arrays as a target also came with webpack 5. Arrays are listed as a valid type in the [webpack 5 docs](https://webpack.js.org/configuration/target/#target), but not in the [webpack 4 docs](https://v4.webpack.js.org/configuration/target/#target)

**Comment by irfanit93** [comment]
> > Not sure if that helps, but it looks like this problem also occurs when the target is an array.
> > For example: `target: 'web'` works, but `target: ['web']` don't.
> 
> Yup, the ability to set arrays as a target also came with webpack 5. Arrays are listed as a valid type in the [webpack 5 docs](https://webpack.js.org/configuration/target/#target), but not in the [webpack 4 docs](https://v4.webpack.js.org/configuration/target/#target)
> 
> EDIT: If it helps, my current fix is to specify "web" as a target when developing and "browserslist" as a target when building for production:
> 
> ```js
> target: process.env.NODE_ENV === "development" ? "web" : "browserslist",
> ```

Removing the target property from webpack.config.js also works fine for me for development purpose.
As you said we can later add the target property when we are building for production.

**Comment by daniele-orlando** [comment]
After struggling 1 day I confirm that having a `browserslist` file inside the root of the project breaks the HMR.
`webpack 5.2`
`webpack-cli 4.1`
`webpack-dev-server 3.11`
`babel-loader 8.1.0`

Everything was behaving as expected with webpack 4.

**Comment by pegiadise** [comment]
> After struggling 1 day I confirm that having a `browserslist` file inside the root of the project breaks HMR.
> `webpack` **5.2**
> `webpack-cli` **4.1**
> `webpack-dev-server` **3.11**
> `babel-loader` **8.1.0**
> 
> Everything was behaving as expected with webpack 4.
> 
> Forcing `target: 'web'` restores the HMR functionality, even with the `browserslist` file in place.

I will add that declaring `browserslist` entry in your `package.json` also reproduces this. Doing the `target` workaround for now.

**Comment by gerhat** [comment]
Another option is to declare the browserslist in `babel.config.js` using the `targets` option of `babel-preset-env` as described here: https://babeljs.io/docs/en/babel-preset-env#targets

A working presets array in `babel.config.js` looks like this:
```javascript
  presets: [
    [
      path.resolve(__dirname, 'node_modules', '@babel/preset-env'),
      {
        useBuiltIns: 'entry',
        corejs: 3,
        targets:
          'defaults, not ie < 11, last 2 versions, > 1%, iOS 7, last 3 iOS versions',
      },
    ],
    path.resolve(__dirname, 'node_modules', '@babel/preset-react'),
    path.resolve(__dirname, 'node_modules', '@babel/preset-typescript'),
  ],
```

**Comment by evilebottnawi** [comment]
Fixed in v4 branch (release will be soon)

**Comment by khalwat** [comment]
Thank you for all you do @evilebottnawi !

**Comment by eladchen** [comment]
Heh.. Just spent 2 hours trying to trace the root cause.. 🤯

**Comment by moxxuk** [comment]
> Not sure if that helps, but it looks like this problem also occurs when the target is an array.
> For example: `target: 'web'` works, but `target: ['web']` doesn't.

[According to docs](https://webpack.js.org/concepts/targets/#multiple-targets), "Although webpack does not support multiple strings being passed into the target property, you can create an isomorphic library by bundling two separate configurations..."

**Comment by evilebottnawi** [comment]
@moxxuk Can you open an issue in webpack docs repo? We should fix it

**Comment by Jaffsterz** [comment]
Adding "target: web" fixed it for me but unfortunately means my dev environment no longer builds for IE11 - is there a way to get both working?

**Comment by ShevchukOleg** [comment]
Guys and Ladies
read this: https://openbase.io/js/webpack-dev-server/versions
npm i webpack-dev-server@4.0.0-beta.0
devServer: { static: true }

**Comment by khalwat** [comment]
Yep @ShevchukOleg  , I have `webpack-dev-server` version `^4.0.0-beta.0` up and working in my config, and it's wonderful. It fixes the `target: 'web'` issue mentioned in this thread, too.

Thank you to @alexander-akait & the whole team for your hard work on this!

**Comment by dossy** [comment]
Will this fix be backported to v3 at all?

**Comment by alexander-akait** [comment]
No

**Comment by rnnyrk** [comment]
Any update on the new `webpack-dev-server` version to fix the `target: web` workaround?

**Comment by alexander-akait** [comment]
You can try `beta`, in near future we will do the next beta release

**Comment by khalwat** [comment]
@rnnyrk the beta works wonderfully, you can see it in use here: https://github.com/nystudio107/annotated-webpack-config/tree/webpack-5

**Comment by lake2** [comment]
this issue is still existing when you set browserlist in package.json
```json
{
    "browserslist": [
        "ie >= 11",
        "chrome >= 30",
        "iOS >= 8",
        "Android >= 4"
    ],
    "keywords": [],
    "author": "",
    "license": "MIT",
    "dependencies": {
    },
    "devDependencies": {
    }
}
```

**Comment by sterling** [comment]
Following the migration guide to webpack 5, it suggests setting `target: ['web', 'es5']` which ended up breaking live reload: https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11

**Comment by magcius** [comment]
Is there any particular reason that this fix isn't being backported to v3, especially since v4 is still in beta months later?

**Comment by Finesse** [comment]
This problem is still actual in Webpack 5.25.1. I need to combine ES5 with live reload because there are still many enterprises who supports IE 11.

**Comment by Darkzarich** [comment]
The problem is still present in Webpack 5.30.0. Placing this in  `webpack.config.js` solves the issue:
```
target: 'web'
```

**Comment by rynpsc** [comment]
We were also experiencing this to still be broken in `v4.0.0-beta.0` but looks to have been fully resolved in `v4.0.0-beta.1` without the need to specify `target: web`.

```
npm install --save-dev webpack-dev-server@4.0.0-beta.1
```

Tested using webpack  v5.30.0.

**Comment by hcorta** [comment]
In case it helps somebody: 
in our case **(react app)** live reloading stopped working after updating **from webpack v4.30.0 to v5.30.0.**
After some investigations, we found that the **react-hot-loader** config was causing the issue, and that removing it from the project brings the reloading functionality back, loosing the Hot Reload though 😕.
 
Still missing some further investigations to properly identify the exact cause of the problem.

Important to mention that @gaearon has deprecated **react-hot-loader**, and they are moving towards a webpack plugin, still experimental: https://github.com/pmmmwh/react-refresh-webpack-plugin/

Hope that helps 😉

**Comment by alexander-akait** [comment]
@hcorta Do you have this problem https://github.com/webpack/webpack/issues/12964?

**Comment by emilio-martinez** [comment]
Why is this closed? This still seems to be an issue.

Setting `target` to `web` fixed it. Setting aside the non-obvious remedy – doesn't the `browserslist` option basically look at the config and resolve the right `target` to use? If that's the case I'd expect my target to resolve to `web` anyway and proceed as usual, so what's the underlying issue here?

**Comment by alexander-akait** [comment]
Solved for webpack-dev-server@beta, rc and stable release will be soon, closed because it is problem on webpack-dev-server side, not webpack itself

**Comment by sibelius** [comment]
I can confirm using target:web fixes the problem

**Comment by dikshantpatodia** [comment]
For `target: web`, here's my 2 cents:

https://webpack.js.org/blog/2020-10-10-webpack-5-release/#improved-target

**Comment by mozhs** [comment]
The latest stable version in npm is still `webpack-dev-server@3.11.2`, and this issue was fixed in latest rc version:

```shell
npm i webpack-dev-server@4.0.0-rc.0
```

Looking forward to the release of the stable version of v4, thanks for your hard work 😛

**Comment by testacode** [comment]
I'm having this issue looping endlessly with '"webpack-dev-server": "^4.0.0-rc.0"

![image](https://user-images.githubusercontent.com/1852080/128431991-24e4c1a8-d6a2-4aeb-8f53-6e63a771014e.png)

**Comment by getsetgopi** [comment]
> Following the migration guide to webpack 5, it suggests setting `target: ['web', 'es5']` which ended up breaking live reload: https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11

I'm having the same issue. Any solution found?

**Comment by xavierfoucrier** [comment]
Hi @alexander-akait,

Thanks for the latest `webpack-dev-server@4.0.0` release :tada:

After upgrading using the migration guide, I just removed the `target: web` workaround, and upgrade my dev server configuration too, but unfortunately, when I change a template page - like html, twig, handlebars or something - it doesn't reload the web browser and I am stuck with:

```console
[HMR] Checking for updates on the server...
[HMR] Nothing hot updated.
[HMR] App is up to date.
```

But it compiles and another `main.****.hot-update.js` file is emitted.
It's just that the browser doesn't properly reloads.

For now, I can fix the issue by setting `hot: false`.

Here is my dev server configuration:

```js
devServer: {
  // hot: true,
  host: 'localhost,
  port: 80,
  static: {
    serveIndex: false,
    staticOptions: {
      watchContentBase: true,
      contentBase: [
        path.join(__dirname, 'src'),
        path.join(__dirname, 'wds'),
      ],
    },
  },
  open: true,
  historyApiFallback: true,
},
```

Thanks for your answer and let me know if I need to create a dedicated issue for that.

> Note that when updating javascript or css, it works fine.

**Comment by alexander-akait** [comment]
Do you have multi compiler mode?, how generate `html`/`twig`/etc, how you load them, note - we have the `watchFiles` options, there you can add additional paths to watch

**Comment by alexander-akait** [comment]
Also:
```
contentBase: [
        path.join(__dirname, 'src'),
        path.join(__dirname, 'wds'),
      ],
```

is invalid, `static.directory: [path.join(__dirname, 'src'), path.join(__dirname, 'wds')]` is valid, but you don't need to watch `src`, because webpack already reloads them when you do changes

**Comment by xavierfoucrier** [comment]
Thanks @alexander-akait,

I probably missed the `static.directory` part, so I will have a look at it shortly and give a feedback here.
In addition I am using `twig-html-loader` and `html-webpack-plugin`, so I guess it's just related to the `directory` option.

> Great work on the v4 anyway :wink:

**Comment by alexander-akait** [comment]
> In addition I am using twig-html-loader and html-webpack-plugin, so I guess it's just related to the directory option.

hm, `index.html` (other html files) should be handled by `webpack-dev-middleware` by default without any additional options, where you store public files for server?

**Comment by xavierfoucrier** [comment]
@alexander-akait The webpack output is set to a `wds` folder, managed "in memory" by `webpack-dev-server`, and I got my views/components/templates twig source files inside the `src` folder.

```js
output: {
  filename: 'app.js',
  path: path.join(__dirname, 'wds'),
},
```

> I have a meeting right now, but I will check for the `directory` option when I am back. Thanks!

**Comment by alexander-akait** [comment]
you can set `watchFiles: ["views/**/*.twig"]`

**Comment by xavierfoucrier** [comment]
@alexander-akait Thanks for the feedback!

I have completely removed the `staticOptions` and setup the `directory` for my static files. I also removed `wds` + `src` watch content base (old) option. After that, all edited twig files triggers a new compilation, but still no browser reload. With `hot: false`, it works, weird :thinking:

Then I have set the `watchFiles` option to `['src/**/*.twig']` with `hot: true`: it works!
Every file change trigger a compilation and browser reload.

Is that configuration looks fine to you or should I share my private repo with you for further check?
Thanks a lot mate :wink:

**Comment by alexander-akait** [comment]
@xavierfoucrier I did not quite understand, do you still have problems? :smile:

**Comment by xavierfoucrier** [comment]
@alexander-akait It works fine with the new `watchFiles` option, the weird thing is that without, it still watch for file changes but do no recompilation, unless I set `hot: false`. Is that looks normal to you? Thanks!

**Comment by alexander-akait** [comment]
oh, maybe you have loader or plugin for generating or something else, if you provide reproducible step I will say you what is wrong

**Comment by xavierfoucrier** [comment]
Thanks @alexander-akait, I am in vacation right now, so when I have time, I will send you an invite to a private repo in order for you to have a short look. :wink:

**Comment by alexander-akait** [comment]
Feel free to ping me

**Comment by xavierfoucrier** [comment]
Hello @alexander-akait, I just send you an invite.

Clone, switch to branch `feat/upgrade-wds` then comment `watchFiles` option in webpack `dev` configuration, and finally `npm run dev`. Feel free to open a PR on the repo and share comments inside it :wink: 

Thanks a lot mate! :beers:

**Comment by alexander-akait** [comment]
@xavierfoucrier sorry for delay, I got sick covid, but I'm already better, I'll see tomorrow

**Comment by akphi** [comment]
@alexander-akait hope you get well soon!

**Comment by khalwat** [comment]
I have a working HMR setup here, in case it's useful to anyone:

https://github.com/nystudio107/craft/blob/craft-webpack/buildchain/webpack-configs/dev-server.config.js

**Comment by xavierfoucrier** [comment]
@alexander-akait no problem! Take care of yourself first ✌💊

**Comment by myou11** [comment]
Hi there, I have read through this thread and am not sure why the webpack config for my project does not seem to be working. I know that [webpack-dev-server 4.0.0 recently came out a few weeks ago](https://github.com/webpack/webpack-dev-server/tags) and has removed the need for a workaround of `target: 'web'` when you have `browserslist` in your package.json. I also have `hot: true` in my `devServer` config object and have not included the `HotModuleReplacementPlugin` in my webpack config since webpack 5 will include it automatically when `hot: true` is set.
Aside from that, I'm not sure why my config is not working. I have stripped out my config [in this repo](https://github.com/myou11/webpack5-hot-reload-issue-reproduction) so others can see.
[I did find this other project](https://github.com/carlrip/react-typescript-eslint-webpack) that seems to be using the most up to date webpack dependencies (webpack 5 and webpack-dev-server 4) and theirs hot reloads just fine.
You'll notice that in my project, the only console output I get is:
```
[HMR] Waiting for update signal from WDS...
```
In the other project by carlrip, they get console output of:
```
[HMR] Waiting for update signal from WDS...
[webpack-dev-server] Hot Module Replacement enabled.
[webpack-dev-server] Live Reloading enabled.
```
I think part of my problem is that I'm not getting those last two console logs. Thank you for any help!

**Comment by alexander-akait** [comment]
Remove `client: false`

**Comment by myou11** [comment]
> Remove `client: false`

ah, thank you @alexander-akait! I am assuming that by setting `client: false`, I also disabled the [webSocketTransport](https://webpack.js.org/configuration/dev-server/#websockettransport) property which is how my browser communicates with the webpack-dev-server. I was only intending to disable the overlay, so in effect, I should have only disabled that property specifically:
```js
client: {
    overlay: {
        errors: true,
        warnings: false,
    },
}
```

**Comment by alexander-akait** [comment]
Anyway why you disable warnings? You can filter them, it is better

**Comment by myou11** [comment]
Ah I just didn't want the warnings to show on the overlay, but they still show in the console in the browser and in my terminal. By filtering, are you talking about this [stats object](https://webpack.js.org/configuration/stats/#statswarningsfilter)? I am unfamiliar with filtering

**Comment by alexander-akait** [comment]
@myou11 this https://webpack.js.org/configuration/other-options/#ignorewarnings, ideally you should not have warnings at all or control them by filtering

**Comment by alexander-akait** [comment]
@xavierfoucrier 

> This invitation has expired.

:disappointed: 

Can you send invite again, sorry...

**Comment by xavierfoucrier** [comment]
@alexander-akait done again 😉✌

**Comment by alexander-akait** [comment]
@xavierfoucrier here interesting case, because `hot: true` by default we are trying to apply hot replacement, but without `watchFiles` dev server doesn't known what change in your twig template requires live reload, for this case we implement `watchFiles`, yes, webpack recompiling changes `twig` templates due `twig-html-loader`, in theory we can get `updatedModules` and check if it is empty it means nothing was changed and if compilation hash was changed it means you need to reload browser, I think we can mark this as feature

**Comment by xavierfoucrier** [comment]
@alexander-akait Ha ok I understand. Glad to share interesting use case with webpack team 🍻😉 I will follow the associated issue, just let me know if you still need access to the repository because it will evolve in the near weeks. Thanks!

**Comment by alexander-akait** [comment]
@xavierfoucrier yep, I will ping you if will need more information (but I have local version)

**Comment by dbehmoaras** [comment]
having the same issue. tried every single fix mentioned here and still no luck......

**Comment by alexander-akait** [comment]
@dbehmoaras Please provide reproducible test repo

**Comment by dbehmoaras** [comment]
Sure thing @alexander-akait thank you for offering your help. Please see below for a link to the repo. The app itself doesn't do anything yet. I've been focused on setting up the environment first before adding any functionality. The issue I'm running into is that when I change the text content inside of App.tsx, the change is only reflected after manually re-building bundle.

https://github.com/ResearchGlobal/stockwatch

The hierarchy is as follows: index.tsx renders App.tsx, which only includes a single <div> with some inner HTML. Feel free to ignore the Context provider for the time being as well as the testing suite. There is also a server.ts file which handles the back end inside the server directory. To get started - npm install, npm run build, and then npm run dev.

**Comment by alexander-akait** [comment]
>  <w> [webpack-dev-server] "hot: true" automatically applies HMR plugin, you don't have to add it manually to your webpack configuration.

remove:
```
new webpack.HotModuleReplacementPlugin({
      template: "./index.html",
    }),
```

It is automatically enable when `hot: true` (default).


```
static: {
      publicPath: "./build",
    },
```

to

```
static: {
      directory: "./build",
    },
```    
Other note:

```
resolve: {
    // `...` extends default extensions + your add own
    extensions: [".web.js", ".ts", ".tsx", "..."],
  },
```

But the main problems is here:
```
proxy: {
      "/": {
        target: `http://localhost:${process.env.SERVER_PORT}`,
        secure: false,
      },
    },
```

You proxy all request to your server, you need keep, for example:
```
// Only HTML passed to your server
proxy: {
      "/": {
        target: `http://localhost:${process.env.SERVER_PORT}`,
        secure: false,
        bypass: function (req, res, proxyOptions) {
          if (req.headers.accept.indexOf('html') !== -1) {
            console.log('Skipping proxy for browser request.');
            return '/index.html';
          }
        },
      },
    },
```

Also not you need to add `build/index.html` - `<div id="root"></div>`

**Comment by dbehmoaras** [comment]
@alexander-akait thank you very much. I will try this right away and let you know if it helps.

**Comment by dbehmoaras** [comment]
@alexander-akait worked like a charm! Thank you very much for your help! I am very grateful

**Comment by dbehmoaras** [comment]
@alexander-akait quick follow up - if i add a proxy, is it correct to assume that i would need to add the bypass in the same way?

**Comment by alexander-akait** [comment]
If your requests are overlapping, i.e. you have `/public/image.png` for main server and `/public/image.png` for dev server, hard to say what is the better for you, I think you need handle only `html` based requests

**Comment by dbehmoaras** [comment]
ok that makes sense, thanks!

**Comment by shenjo** [comment]
> Remove `client: false`

that's works for me. Could you please update the [guides](https://webpack.js.org/guides/hot-module-replacement/) ? As following the guide doesn't work.

**Comment by Jingotto** [comment]
I also had a problem with the DevServer, the pages were not refreshed. I added this code and it helped me.

  static: {
      directory: path.join(__dirname, 'src'), 
      watch: true,
    },

P.S. Maybe I didn’t understand the problem, sorry, i’m a noob. But if someone faced the same problem it helps.

**Comment by vaibhav023** [comment]
> Feel free to ping me

**Comment by CHENJIAMIAN** [comment]
use cnpm install , resolve.symlinks: false,  make it happen.
You can see this [troubleshooting.html#symbolic-links-in-node-modules](https://cli.vuejs.org/guide/troubleshooting.html#symbolic-links-in-node-modules)

**Comment by amrfhn** [comment]
Hello, i come from  2022, is there any updates regarding the live reloading issue?
