### ISSUE TITLE
HMR not working with multiple entries

### ISSUE THREAD

**Issue by slightlyfaulty** [webpack/webpack-dev-server#2792]
- Operating System: Linux
- Node Version: 14.14.0
- NPM Version: 6.14.7
- webpack Version: 5.2.0
- webpack-dev-server Version: 3.11.0
- Browser: Google Chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

https://github.com/slightlyfaulty/webpack-hmr-multi-entry-repro

```js
// webpack.config.js
...
entry: {
  first: ['./src/first.js', './src/first.css'],
  second: ['./src/second.js', './src/second.css'],
},
...
```

### Expected Behavior

After starting the dev server, hot module replacement should work for all JS and CSS files from all webpack entries.

### Actual Behavior

Hot module replacement doesn't work for all entries. Only files from the second entry are hot reloaded when changed. Files from the first entry do not get hot reloaded when changed.

### For Bugs; How can we reproduce the behavior?

1) Clone repro then `yarn && yarn start`
1) Open http://localhost:8080/
1) Change `src/first.js` and `src/first.css` - notice they are ***not*** hot reloaded
1) Change `src/second.js` and `src/second.css` - notice they ***are*** hot reloaded

**Comment by MohsenElgendy** [comment]
@slightlyfaulty setting `optimization.runtimeChunk: "single"` fixed the problem for me.

**Comment by slightlyfaulty** [comment]
Thanks for the tip @MohsenElgendy, but it's still not really ideal as you need to then load the `runtime` chunk alongside your other bundles. Webpack 4 handled embedding the runtime in multiple bundles at the same time no problem.

**Comment by waldronmatt** [comment]
I can also confirm optimization.runtimeChunk: "single" fixed the problem for me handling multiple bundles.

webpack.dev.config
```
module.exports = () => {
  const config = {
    mode: 'development',
    // Map your compiled code back to your original source code.
    devtool: 'inline-source-map',
    target: 'web',
    output: {
      filename: '[name].js',
      // specify chunck path for code splitted files
      chunkFilename: '[name].js',
    },
    devServer: {
      historyApiFallback: true,
      contentBase: path.resolve(__dirname, '../dist'),
      publicPath: '/',
      open: true,
      compress: true,
      hot: true,
      port: 8080,
    },
    plugins: [
      new ESLintPlugin({
        extensions: ['js', 'ts'],
      }),
      new StylelintPlugin(),
      new webpack.HotModuleReplacementPlugin(),
    ],
    optimization: {
      // don't minimize so we can debug
      minimize: false,
      /*
        The value 'single' instead creates a runtime file to be shared for all generated chunks.
        https://github.com/webpack/webpack-dev-server/issues/2792
      */
      runtimeChunk: "single",
    },
  };
  return merge(common('development'), config);
};
```

webpack.common.js

```
module.exports = (env) => {
  const isProduction = env === 'production';

  ...

  return {
    target: 'web',
    entry: {
      main: [
        './src/js/index.js',
        './src/ts/index.ts',
      ],
      // webpack code splitting example file
      examples: [
        './src/js/examples.js',
      ],
    },
    output: {
      path: path.join(__dirname, '../dist'),
      publicPath: '/',
    },

  ...

};
```

**Comment by uxsoft** [comment]
Same issue here, setting optimization.runtimeChunk: "single" fixed the problem for me as well, but I would consider this a workaround for a bug that should be fixed anyway. This certainly worked before.

**Comment by evilebottnawi** [comment]
I think it fixed in v4 branch, you can try it

**Comment by slightlyfaulty** [comment]
@evilebottnawi Can't test properly because it seems `writeToDisk` has been removed in v4 for some reason?

Initial compilation also takes much longer than the regular build time now. Over 6 seconds compared to <2 seconds for regular build. On v3 it only takes about 2.2 seconds for the initial dev server compilation.

**Comment by evilebottnawi** [comment]
It was not removed, it was moved to `dev: { writeToDisk: true }`

**Comment by evilebottnawi** [comment]
There is not changes between v3 and v4 in perf

**Comment by slightlyfaulty** [comment]
> It was not removed, it was moved to `dev: { writeToDisk: true }`

Aha.. that's working now, but can confirm this bug is still present. Only the last loaded bundle in the document hot reloads properly. Bundles from other entries do not hot reload at all.

Also had to explicitly disable `liveReload`, otherwise it live reloaded the page after every change, even though `hot` is enabled.

> There is no changes between v3 and v4 in perf

Evidence would suggest otherwise sir. Will open an issue after release of v4 if it persists.

**Comment by evilebottnawi** [comment]
@slightlyfaulty Please create reproducible test repo, it should work

**Comment by slightlyfaulty** [comment]
@alexander-akait Sure. https://github.com/slightlyfaulty/webpack-hmr-multi-entry-repro

1. `yarn && yarn start` - Open http://localhost:8080/
1. Change `src/first.js` and `src/first.css` - notice they are not hot reloaded, and there are some errors in the browser console
1. Change `src/third.js` and `src/third.css` - notice they are hot reloaded correctly, because they're loaded last in the page

**Comment by onetrev** [comment]
Is there a reason to avoid multiple entry points / bundles, because I'm surprised that not a ton of people are also reporting this bug? I know I need to have them. One example is I need certain things loaded in my site header and the rest at the end of the body.

One thing to note / add to the error report from @slightlyfaulty, I noticed all the console messages come in as warnings not errors, even though indeed HMR spews out a tons of warning messages like so:

```
[HMR] Update failed: Loading hot update chunk site_header failed.
(missing: https://localhost:3018/dist/site_header.3fb54bab211f3a92bb04.hot-update.js)
loadUpdateChunk/<@https://localhost:3018/dist/site_header.bundle.js:10391:26
```

**Comment by andywang646691** [comment]
same issue.

**Comment by wangmeijian** [comment]
same issue

**Comment by Connum** [comment]
Any news on this? I don't want to have to downgrade several packages to get it to work, and this is really slowing down development...

**Comment by pixelhuh** [comment]
Exactly the same problem and same warnings as @onetrev on webpack 5.9.18 
On 4.46 HMR for multiple entries works fine.

**Comment by koen-dev** [comment]
I also encountered this issue with multiple entries. However setting `optimization.runtimeChunk: "single"` didn't work. I'm using multiple `HtmlWebpackPlugin`s to serve the entries as solo applications. What is the best step for now? Move back to `webpack@4.46.0`?

**Comment by ZukenHammer** [comment]
Also encountered this issue. Setting `optimization.runtimeChunk: "single"` is not working for me. I need to output my code as library. Using `webpack@5.24.2` and `webpack-dev-server@4.0.0-beta.0`. Current working solution is to set `hot: false`.

**Comment by alexander-akait** [comment]
Please test https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.1, we will speed up releases, to be stable at the end of month

**Comment by slightlyfaulty** [comment]
@alexander-akait Nope no change to the issue.

https://github.com/webpack/webpack-dev-server/issues/2792#issuecomment-734406486

**Comment by alexander-akait** [comment]
@slightlyfaulty Found solution:

```html
<script type="text/javascript" src="dist/runtime.js"></script>
<script type="text/javascript" src="dist/first.js"></script>
<script type="text/javascript" src="dist/second.js"></script>
<script type="text/javascript" src="dist/third.js"></script>
```

```
optimization: {
  runtimeChunk: 'single'
},
```

**Comment by slightlyfaulty** [comment]
@alexander-akait That solution has already been [posted before](https://github.com/webpack/webpack-dev-server/issues/2792#issuecomment-724169118).

It's more of a workaround than a solution though don't you think? Since it worked fine in Webpack 4 without needing to enqueue a runtime bundle.

**Comment by alexander-akait** [comment]
@slightlyfaulty Here are multi entries on one page... so we have multiple `__webpack_require__` with HMR, each `__webpack_require__` known only about own modules and HMR status, when we get update we will run multiple of them, so you can see `[HMR] Update failed: ChunkLoadError: Loading hot update chunk first failed.` and `[HMR] Update failed: ChunkLoadError: Loading hot update chunk second failed.`

**Comment by alexander-akait** [comment]
Give me time to look at this deeply, but I don't think bug in webpack-dev-server, I think it is bug with webpack here

**Comment by slightlyfaulty** [comment]
> Give me time to look at this deeply, but I don't think bug in webpack-dev-server, I think it is bug with webpack here

@alexander-akait No problem. All I know is it worked fine with the Webpack 4 stack, so it's a regression one way or another.

**Comment by alexander-akait** [comment]
@slightlyfaulty Maybe it is limitation, I want to get answer from @sokra, in this case we should share `./node_modules/dev-server/client/default/index.js` and `./node_modules/webpack/hot/dev-server.js` between entry points, i.e. create shared/runtime chunk, but without `optimization.runtimeChunk`, webpack doesn't do it, If we initially knew how you would use them (for example from index.html) we can apply `runtimeChunk` optimization by default.

https://webpack.js.org/configuration/optimization/#optimizationruntimechunk

we have warning about it

> Warning
> Imported modules are initialized for each runtime chunk separately, so if you include multiple entry points on a page, beware of this behavior. You will probably want to set it to single or use another configuration that allows you to only have one runtime instance.

**Comment by alexander-akait** [comment]
Other idea - output the warning in runtime and provide example how to fix it for better DX

**Comment by sokra** [comment]
Running multiple entries on a single page **that do not share a runtime chunk** (e. g. with `runtimeChunk: single`) from the same compilation are not supported. Please use a shared runtime chunk. There are weird side effects when doing this. Seems like HMR not working is one of them.

**Comment by slightlyfaulty** [comment]
@sokra If it's not possible in Webpack 5 then fair enough. I think there are just a lot of people, like myself, who were doing this in Webpack 4 and it worked perfectly out the box.

Perhaps this limitation of Webpack 5 should be added to the migration guide if it isn't already.

**Comment by xuya227939** [comment]
@alexander-akait Hi，I had same problem，what is the current solution?  I use `webpack：4.41.2`，`webpack-dev-server：3.10.1`

**Comment by alexander-akait** [comment]
Should work for v4, try to update webpack-dev-server tom `3.11.x` version

**Comment by xuya227939** [comment]
@alexander-akait Hi，I tried to upgrade webpack dev server: ^ v4.0.0-beta.2, but I still couldn't. I provided a reproducible warehouse, address: https://github.com/xuya227939/tristana，Branch webpack-dev-server, `git clone`, and then `$ npm i`, `$ npm start` to reproduce. Please help to have a look.

**Comment by xuya227939** [comment]
@alexander-akait Please ignore， I solved it.

**Comment by tianyingchun** [comment]
what's progress of this bug? i tested `"webpack-dev-server": "^4.0.0-rc.0",` && "webpack": "^5.47.1", 
for multi enties with dynamic `import() ` don't work correct, it will infinite loop for `update.json`
![image](https://user-images.githubusercontent.com/2833251/128813297-9fc86b4c-b4d6-456d-8721-d764cb781efd.png)

**Comment by alexander-akait** [comment]
Update webpack to the latest version

**Comment by tianyingchun** [comment]
yes, the latest webpack work fine.

**Comment by tianyingchun** [comment]
HI, @alexander-akait 
`for HMR not working with multiple entries` 
i upgrade webpack-dev-server from `v4.0.0-rc.1` to `v4.0.0`  it will infinite loop for update.json 404.
 i use `"webpack": "^5.50.0",`
BTW:  
`webpack-dev-server@4.0.0-rc.1` with webpack@^5.50.0` it work fine.
`webpack-dev-server@4.0.0` with webpack@^5.50.0` was broken,  infinite loop for update.json

**Comment by Kaiynn** [comment]
Imported modules are initialized for each runtime chunk separately, so if you include **multiple entry points on a page**, beware of this behavior. You will probably want to set it to **single or use another configuration** that allows you to only have one runtime instance. From [https://webpack.js.org/configuration/optimization/#optimizationruntimechunk](https://webpack.js.org/configuration/optimization/#optimizationruntimechunk).This method helped me solve the problem.

**Comment by erikt9** [comment]
One thing that I've found is that even if you are following all the suggestions above, you will still have problems if you are using multiple compilers that have the same entrypoint names (for example if you have one compiler creating es5 code, another generating more modern code, and they share the same entrypoint configuration).

**Comment by alexander-akait** [comment]
@erikt9 What is the problem? Infinity loop? Can you provide example?

**Comment by erikt9** [comment]
> @erikt9 What is the problem? Infinity loop? Can you provide example?

The problem I was having looks to be fixed in 4.2.1.  Thank you!

**Comment by sidekick101** [comment]
I'm facing a similar problem from following the exact steps in the get started guide in the official website. Except I get the following error after the first edit of `./src/index.js`: 

![image](https://user-images.githubusercontent.com/49096097/135760811-9a368c7a-14ba-4c4e-8712-e673652dbf31.png)

If I try to edit it again and save, I get this: 

![image](https://user-images.githubusercontent.com/49096097/135760867-147453e9-9353-45bc-9942-8eaca1d2ba50.png)

It's like I didn't even change anything. Removing the second entry point makes it work as expected.

as I said, my `webpack.config.js` is exactly like the one in the get started guide: 

```
 const path = require('path');
 const HtmlWebpackPlugin = require('html-webpack-plugin');

 module.exports = {
   mode: 'development',
   entry: {
     index: './src/index.js',
     print: './src/print.js',
   },
   devtool: 'inline-source-map',
  devServer: {
    static: './dist',
  },
   plugins: [
     new HtmlWebpackPlugin({
       title: 'Development',
     }),
   ],
   output: {
     filename: '[name].bundle.js',
     path: path.resolve(__dirname, 'dist'),
     clean: true,
   },
 };
```
The only difference is that the webpack-dev-server in the guide is `^3.11.0` meanwhile I have `^4.3.0`.

**Comment by alexander-akait** [comment]
You can't use multiple entries on the same page, please use https://github.com/webpack/webpack-dev-server/issues/2792#issuecomment-806983882

**Comment by stevematney** [comment]
I was able to get multiple entries working with a _very_ hacky solution involving hijacking `self["webpackHotUpdate"]` with a `window` Proxy, utilizing a Service Worker, and which relies on another plugin that wraps the built entry bundle in a self-calling function for isolation.

It was... a lot, but eventually I got everything working smoothly. It doesn't always guarantee the updates get to the correct place if two modules are updated at the same time that have the same ID across bundles, but contain different code. This seems like a very rare case, and for our purposes, this solution is working well enough (though it's quite complex).

**Comment by ayroblu** [comment]
Hi, just wanted to follow up with whether there's an alternative solution to the `runtimeChunk` solution? I found that using that with monaco-editor causes it to fail to load results.
In the meantime I can set `hot: false`. And the main difference is that I no longer have css hot reloading.

**Comment by chenwenqin** [comment]
![image](https://user-images.githubusercontent.com/32031718/155061851-683f2fb0-f3e1-4e0c-8de4-9e9839b25aca.png)

webpack@5.66.0

only in production mode, but not in development mode, whether it is enabled or not optimization option。

**My project only one entry**.

**Comment by alexander-akait** [comment]
@chenwenqin Can you provide reproducible example?

**Comment by khelkun** [comment]
@alexander-akait 
> You can't use multiple entries on the same page, please use [#2792 (comment)](https://github.com/webpack/webpack-dev-server/issues/2792#issuecomment-806983882)

Indeed it works but if I well understand, you need to include the runtimeChunk aka `runtime.js` before the others entry chunks.

Considering my app is actually a library used by others applications, this solution forces all dependent apps to include this new `runtime.js` before my library entries.

Would there be a way to embed this runtimeChunk in the chunk in the first entry of my library?

**Comment by slightlyfaulty** [comment]
@khelkun I recently discovered that if you use the [dependOn](https://webpack.js.org/concepts/entry-points/#entrydescription-object) option for an entry, then it will use the runtime that's embedded in the entry it depends on.

In this case you don't need to use `runtimeChunk: 'single'` anymore, as long as the `dependOn` entry is always loaded first.

**Comment by shalkauskas** [comment]
@slightlyfaulty thank you, worked great with webpack 5!

**Comment by bradyclifford** [comment]
@slightlyfaulty  you wouldn't happen to have an example you could share with the `dependOn` working for you?

**Comment by slightlyfaulty** [comment]
@bradyclifford I've pretty much just got my entry points listed like the examples in the docs. Nothing special.

https://webpack.js.org/concepts/entry-points/#entrydescription-object

**Comment by thebat93** [comment]
I'm having a problem with HMR when Webpack has multiple entries and one of them is a service worker.

If I use `runtimeChunk: 'single'` hot reloading works as intended. But none of service worker's hooks runs.

I found [this solution](https://stackoverflow.com/questions/72114876/webpack-transpiled-typescript-service-worker-code-doesnt-seem-to-work). With this service worker's hooks run, but this breaks hot reloading. When I try to update the app code I get warnings and nothing gets updated:
`[HMR] Update failed: ReferenceError: document is not defined`
`[HMR] Update failed: ChunkLoadError: Loading hot update chunk runtime-app failed.`

Has anyone faced this problem? I'm using Webpack 5 with the following options:
```
entry: {
  app: ['/index.tsx'],
  'service-worker': '/service-worker.js',
},
output: {
  filename: pathData => {
    if (pathData?.chunk?.name === 'service-worker') {
      return '[name].js';
    }
    return '[name].[contenthash].bundle.js';
  },
},
optimization: {
    runtimeChunk: {
      name: (entrypoint) => {
        if (entrypoint.name.startsWith("service-worker")) {
          return null;
        }
        return `runtime-${entrypoint.name}`;
      },
    },
    splitChunks: {
      chunks(chunk) {
        return chunk.name !== "service-worker";
      },
      cacheGroups: {
        default: false,
        vendors: false,
        framework: {},
        lib: {},
        commons: {},
        shared: {},
        styles: {}
      },
      maxInitialRequests: 25,
      minSize: 20000
    },
},
```

**Comment by thebat93** [comment]
Here is a minimal test repo with the issue: https://github.com/thebat93/sw-webpack-hmr
I mentioned solutions that I tried in webpack config file.

**Comment by develobora** [comment]
Not working for me also with multiple entries. "webpack": "^5.53.0", "webpack-dev-server": "^4.7.4".

**Comment by alexcloudstar** [comment]
> @slightlyfaulty Found solution:
> 
> ```
> <script type="text/javascript" src="dist/runtime.js"></script>
> <script type="text/javascript" src="dist/first.js"></script>
> <script type="text/javascript" src="dist/second.js"></script>
> <script type="text/javascript" src="dist/third.js"></script>
> ```
> 
> ```
> optimization: {
>   runtimeChunk: 'single'
> },
> ```

Thank you! is working perfectly fine.

Here is a part of my package.json (i'm doing micro-frontends btw I don't know if is matter or not because I do have the same packages isntalled)

```
"scripts": {
    "start": "webpack serve --config config/webpack.dev.js",
    "build": "webpack --config config/webpack.prod.js"
  },
```

devDeps:
```
"babel-loader": "^9.1.3",
"webpack": "^5.88.1",
"webpack-cli": "^5.1.4",
"webpack-dev-server": "^4.15.1",
"webpack-merge": "^5.9.0"
"babel-loader": "^9.1.3",
"html-webpack-plugin": "^5.5.3",
"typescript": "^5.1.6",
"@babel/core": "^7.22.8",
"@babel/plugin-transform-runtime": "^7.22.7",
"@babel/preset-env": "^7.22.7",
"@babel/preset-react": "^7.22.5",
```

**Comment by slightlyfaulty** [comment]
Closing this. In Webpack 5 `optimization.runtimeChunk: "single"` and/or [`dependOn`/`runtime`](https://webpack.js.org/concepts/entry-points/#entrydescription-object) should be used appropriately to control where the runtime is embedded. Otherwise each entry contains a runtime resulting in this issue.

**Comment by trystan2k** [comment]
> posted before

Hi @slightlyfaulty,

I am trying to setup a simple Module Federation with Webpack and HMR project but I cannot make it work correctly.

I have went down to the minimal case that does not work, to be sure I am starting right and then going up but it is failing in the first step.

I have uploaded the project here : https://stackblitz.com/edit/webpack-webpack-js-org-exj81u?file=apps%2Fremote%2Fsrc%2FApp.tsx

To run it, just open the terminal in stackblitz and do:
1. cd apps/remote
2. npm run dev

Then try to edit the App.tsx and see that it show an error in the console and page is not updated.
This is the error:

<img width="896" alt="image" src="https://github.com/user-attachments/assets/06c02689-462e-4d3c-aee7-535f2475136e">

If I remove the ModuleFederationPlugin from the Webpack config file, the HMR work as expected.

Could you help me find out what is wrong here ?

Thank you !
